name: cross_platform_chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^2.7.0
  flutter_chat_ui: ^1.5.7
  flutter_sound: ^9.2.13+1
  mime: ^1.0.2
  audioplayers: ^5.2.1
  permission_handler: ^11.3.1
  flutter_chat_types: ^3.5.1
  uuid: ^4.4.2
  http: ^1.4.0
  shared_preferences: ^2.0.15
  flutter_gradient_animation_text: ^1.0.2
  background_fetch: ^1.3.8
  path_provider: ^2.1.5
  email_validator: ^3.0.0
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  intl: ^0.20.0
  provider: ^6.0.0
  flutter_svg: ^2.0.7
  matrix: ^0.40.0
  flutter_olm: ^2.0.0
  flutter_vlc_player: ^7.4.3
  flutter_openssl_crypto: ^0.5.0
  flutter_secure_storage: ^9.2.4
  flutter_inappwebview: ^6.1.5
  fluttertoast: ^8.2.4
  ffmpeg_kit_flutter_new: ^1.6.1

  image_picker: ^1.0.4  # ✅ yeni
  video_player: ^2.5.3  # ✅ yeni

  chatview: ^2.4.1
  just_audio: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  firebase_auth_platform_interface: ^7.0.11
flutter:

  uses-material-design: true

  assets:
    - assets/splash_animation.json
    - assets/bluesky-icon.png
    - assets/whatsapp.png
    - assets/instagram.png
    - assets/twitter.png
    - assets/telegram.png
    - assets/backgroundImage.png


  fonts:
    - family: MyTitleFont
      fonts:
        - asset: assets/fonts/ClimateCrisis-Regular-VariableFont_YEAR.ttf
